version: "3"
services:
  clone_gag:
    build:
      context: .
    ports:
    - "8080:8080"
  db:
    image: postgres:10
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - ./src/main/resources/sql/config/init.sql:/docker-entrypoint-initdb.d/init.sql